//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCR
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UsersAcount
    {
        public int AccountId { get; set; }
        public string EmpID { get; set; }
        public string FullName { get; set; }
        public string UserName { get; set; }
        public string NormalPassword { get; set; }
        public string SaltPassword { get; set; }
        public string EmailID { get; set; }
        public Nullable<bool> EmailConfirmed { get; set; }
        public string MobileNumber { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsOnline { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string UserImagePath { get; set; }
        public string Signatures { get; set; }
    }
}
